const json = [
  {
    _id: "652d54500f1407350e9a08d5",
    index: 0,
    guid: "d372d155-8b05-485d-928d-7effaab027ae",
    isActive: false,
    balance: "$1,053.78",
    picture: "http://placehold.it/32x32",
    age: 29,
    eyeColor: "brown",
    name: "Franco Olsen",
    gender: "male",
    company: "DYMI",
    email: "francoolsen@dymi.com",
    phone: "+1 (991) 496-2842",
    address: "131 Oceanic Avenue, Odessa, Hawaii, 7571",
    about:
      "In occaecat dolor quis nisi fugiat. Eu laboris et sunt est anim consectetur quis nulla. Eiusmod reprehenderit deserunt elit ullamco eu cupidatat id eu non laboris ipsum cupidatat voluptate. Eiusmod ea minim elit id ea commodo cillum quis consequat. Quis aliqua in anim occaecat duis enim tempor irure magna velit nisi. Do Lorem quis officia laboris mollit non dolor dolore.\r\n",
    registered: "2022-02-13T05:52:14 -06:-30",
    latitude: 31.698802,
    longitude: 48.658098,
    tags: [
      "occaecat",
      "amet",
      "irure",
      "consectetur",
      "adipisicing",
      "incididunt",
      "laborum",
    ],
    friends: [
      {
        id: 0,
        name: "Salas Torres",
      },
      {
        id: 1,
        name: "Owen Robles",
      },
      {
        id: 2,
        name: "Davenport Arnold",
      },
    ],
    greeting: "Hello, Franco Olsen! You have 1 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "652d5450d7de710a888d2dcd",
    index: 1,
    guid: "5467d628-9792-491b-a902-12e5c482bef2",
    isActive: false,
    balance: "$3,079.29",
    picture: "http://placehold.it/32x32",
    age: 24,
    eyeColor: "blue",
    name: "Mccullough Guerrero",
    gender: "male",
    company: "QUANTALIA",
    email: "mcculloughguerrero@quantalia.com",
    phone: "+1 (943) 569-2028",
    address: "855 Oriental Court, Bartley, Utah, 5901",
    about:
      "Eiusmod aliqua cupidatat excepteur consectetur quis voluptate officia ad in. Eiusmod officia fugiat ea cupidatat exercitation qui do. Sint sunt aliqua labore adipisicing magna fugiat nisi sit. Ipsum voluptate dolore culpa ea fugiat. Sunt deserunt ipsum velit adipisicing.\r\n",
    registered: "2022-08-04T09:46:58 -06:-30",
    latitude: -65.558859,
    longitude: -150.075997,
    tags: ["Lorem", "veniam", "do", "labore", "aute", "ad", "aliquip"],
    friends: [
      {
        id: 0,
        name: "Courtney Short",
      },
      {
        id: 1,
        name: "Celeste Kinney",
      },
      {
        id: 2,
        name: "Powers Good",
      },
    ],
    greeting: "Hello, Mccullough Guerrero! You have 9 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "652d54503252516d7427b02c",
    index: 2,
    guid: "4dab674e-19b9-49e8-b331-83381990df9b",
    isActive: true,
    balance: "$2,488.72",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "brown",
    name: "Marcia Parrish",
    gender: "female",
    company: "TUBESYS",
    email: "marciaparrish@tubesys.com",
    phone: "+1 (806) 476-3894",
    address: "693 Hoyts Lane, Sehili, Ohio, 9688",
    about:
      "Magna et quis aute dolore deserunt. Quis esse labore dolor pariatur aute cupidatat. Culpa veniam esse sunt anim ut veniam amet aliqua. Tempor sunt aliquip ex consequat velit sunt sint do excepteur quis do.\r\n",
    registered: "2017-05-27T08:17:28 -06:-30",
    latitude: 61.697174,
    longitude: -75.16512,
    tags: ["fugiat", "magna", "sunt", "velit", "qui", "anim", "dolor"],
    friends: [
      {
        id: 0,
        name: "Lynne Barrera",
      },
      {
        id: 1,
        name: "Robertson Glass",
      },
      {
        id: 2,
        name: "Herman Richmond",
      },
    ],
    greeting: "Hello, Marcia Parrish! You have 8 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "652d5450ac541e31005d9275",
    index: 3,
    guid: "7135c170-5703-4bb6-8940-497c1625a257",
    isActive: true,
    balance: "$1,509.52",
    picture: "http://placehold.it/32x32",
    age: 23,
    eyeColor: "brown",
    name: "Pace Kline",
    gender: "male",
    company: "EARGO",
    email: "pacekline@eargo.com",
    phone: "+1 (844) 466-2715",
    address: "963 Croton Loop, Waikele, North Carolina, 7371",
    about:
      "Ut cillum Lorem nulla aliqua deserunt officia minim laborum ut nulla voluptate. Ea aliquip elit culpa do laborum. Dolore ea non est sit duis labore. Veniam cupidatat qui ipsum pariatur. Officia velit mollit esse ipsum magna tempor velit. Ipsum est irure velit magna exercitation sint dolore amet et adipisicing aliqua in. Dolor in exercitation proident ipsum nostrud.\r\n",
    registered: "2022-06-03T02:30:43 -06:-30",
    latitude: 83.744223,
    longitude: -6.195632,
    tags: ["veniam", "et", "qui", "non", "occaecat", "tempor", "tempor"],
    friends: [
      {
        id: 0,
        name: "Deirdre Justice",
      },
      {
        id: 1,
        name: "Bridgette Hinton",
      },
      {
        id: 2,
        name: "Russo Hatfield",
      },
    ],
    greeting: "Hello, Pace Kline! You have 6 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "652d54502c7e70232f5e967e",
    index: 4,
    guid: "a09182a4-27aa-4994-aae9-0b24f1b3f462",
    isActive: false,
    balance: "$1,936.62",
    picture: "http://placehold.it/32x32",
    age: 22,
    eyeColor: "green",
    name: "Stevens Gill",
    gender: "male",
    company: "CRUSTATIA",
    email: "stevensgill@crustatia.com",
    phone: "+1 (995) 579-2445",
    address: "530 Bedell Lane, Hayden, South Carolina, 777",
    about:
      "Irure amet aute elit eiusmod pariatur aliquip laboris officia voluptate ex tempor nostrud ea. Cupidatat officia elit ea dolor duis est labore cillum. Ipsum est sunt elit sint ut amet anim exercitation velit pariatur. Commodo Lorem dolor qui sit sunt aliquip dolor ea id voluptate dolore.\r\n",
    registered: "2014-03-18T08:28:44 -06:-30",
    latitude: 24.209509,
    longitude: 61.527345,
    tags: ["voluptate", "sunt", "commodo", "quis", "ad", "ut", "cupidatat"],
    friends: [
      {
        id: 0,
        name: "Belinda Clay",
      },
      {
        id: 1,
        name: "Willa Giles",
      },
      {
        id: 2,
        name: "Weaver Espinoza",
      },
    ],
    greeting: "Hello, Stevens Gill! You have 7 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "652d5450bb7b3524ddf7cc80",
    index: 5,
    guid: "357b0372-5940-4076-891e-00aae088685f",
    isActive: true,
    balance: "$1,215.89",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "green",
    name: "Fletcher Ellison",
    gender: "male",
    company: "VERAQ",
    email: "fletcherellison@veraq.com",
    phone: "+1 (826) 411-2446",
    address: "371 Beaver Street, Wyoming, Oregon, 109",
    about:
      "Fugiat et veniam est anim deserunt proident voluptate sint ea minim proident eu. Cillum esse nisi pariatur est eiusmod ullamco excepteur pariatur laborum ullamco. Excepteur tempor anim anim voluptate elit laborum aliqua nostrud cillum. Aliquip sint est proident laborum velit quis cupidatat reprehenderit ut deserunt minim dolore.\r\n",
    registered: "2018-12-30T10:00:32 -06:-30",
    latitude: 49.278681,
    longitude: 91.04544,
    tags: ["ex", "nisi", "laborum", "excepteur", "deserunt", "voluptate", "id"],
    friends: [
      {
        id: 0,
        name: "Lillie Mcdowell",
      },
      {
        id: 1,
        name: "Lupe Black",
      },
      {
        id: 2,
        name: "Vickie Hodge",
      },
    ],
    greeting: "Hello, Fletcher Ellison! You have 5 unread messages.",
    favoriteFruit: "apple",
  },
];
export default json;
